[tasks.bin]
command = "cargo"
args = ["objcopy", "--target", "${TARGET}", "--", "-O", "binary", "${TOP_LEVEL}/target/${DEVICE_BIN_NAME}-debug.dfu.bin"]

[tasks.bin-dfu]
command = "dfu-suffix"
args = ["--add", "${TOP_LEVEL}/target/${DEVICE_BIN_NAME}-debug.dfu.bin", "--vid", "${BOOT_VID}", "--pid", "${BOOT_PID}"]
dependencies = ["bin"]

[tasks.bin-release]
command = "cargo"
args = ["objcopy", "--target", "${TARGET}", "--release", "--", "-O", "binary", "${TOP_LEVEL}/target/${DEVICE_BIN_NAME}-release.dfu.bin"]

[tasks.bin-dfu-release]
command = "dfu-suffix"
args = ["--add", "${TOP_LEVEL}/target/${DEVICE_BIN_NAME}-release.dfu.bin", "--vid", "${BOOT_VID}", "--pid", "${BOOT_PID}"]
dependencies = ["bin-release"]

[tasks.build]
command = "cargo"
args = ["build", "--target", "${TARGET}"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release", "--target", "${TARGET}"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--target", "${TARGET}", "--", "-D", "warnings"]

[tasks.doc]
env = { "RUSTDOCFLAGS" = "-Dwarnings" }
command = "cargo"
args = ["doc", "--target", "${TARGET}"]

[tasks.flash]
command = "dfu-util"
args = ["--alt", "0", "--download", "${TOP_LEVEL}/target/${DEVICE_BIN_NAME}-debug.dfu.bin"]
dependencies = ["bin-dfu"]

[tasks.flash-release]
command = "dfu-util"
args = ["--alt", "0", "--download", "${TOP_LEVEL}/target/${DEVICE_BIN_NAME}-release.dfu.bin"]
dependencies = ["bin-dfu"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.gdb-server]
command = "cargo"
args = ["xtask", "gdb-server"]

[tasks.gdb-client]
command = "cargo"
args = ["xtask", "gdb-client"]

[tasks.run]
command = "cargo"
args = ["run", "--target", "${TARGET}"]

[tasks.rerun]
command = "cargo"
args = ["run", "--target", "${TARGET}", "--", "--no-flash"]

[tasks.fastrun]
command = "cargo"
args = ["run", "--target", "${TARGET}", "--", "--no-flash"]
dependencies = ["flash"]

[tasks.run-release]
command = "cargo"
args = ["run", "--release", "--target", "${TARGET}"]

[tasks.sanity]
dependencies = [
    "check",
    "clippy",
    "doc",
    "fmt-check",
]

[tasks.nm]
command = "cargo"
args = ["nm", "--target", "${TARGET}"]

[tasks.objdump]
command = "cargo"
args = ["objdump", "--target", "${TARGET}", "--", "--disassemble", "--no-show-raw-insn"]
