name: Rust Linux

on: [push, pull_request]

env:
  PIPENV_ACTIVE: 1
  deb_packages: >-
    dfu-util
    gcc-arm-none-eabi
    ninja-build
    python3-setuptools

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: thumbv7em-none-eabi
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-make
          version: latest
          use-tool-cache: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ env.deb_packages }}
      - name: Install kll compiler
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install kll
      - uses: actions-rs/cargo@v1
        with:
          command: make
          args: check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview
          target: thumbv7em-none-eabi
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-make
          version: latest
          use-tool-cache: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: latest
          use-tool-cache: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ env.deb_packages }}
      - name: Install kll compiler
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install kll
      - uses: actions-rs/cargo@v1
        with:
          command: make
          args: bin-dfu

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-make
          version: latest
          use-tool-cache: true
      - uses: actions-rs/cargo@v1
        with:
          command: make
          args: fmt-check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          target: thumbv7em-none-eabi
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-make
          version: latest
          use-tool-cache: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ env.deb_packages }}
      - name: Install kll compiler
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install kll
      - uses: actions-rs/cargo@v1
        with:
          command: make
          args: clippy
